function selectLink(linkId){$('#'+linkId).attr('checked',true);changeLinkColor(linkId,SELECTED_LINK_COLOR);}
function unselectLink(linkId){$('#'+linkId).attr('checked',false);changeLinkColor(linkId,UNSELECTED_LINK_COLOR);}
function changeLinkColor(linkId,color){$('#'+LINK_ROW_ELEM_ID_PREFIX+linkId).css('backgroundColor',color);}
function onLinkCheck(){if(window.event.srcElement.checked==true){selectLink(window.event.srcElement.id);}else{unselectLink(window.event.srcElement.id);}}
function fixFileName(s){return s.replace(/[\\\/\?\:\*\"\|\>\<]/g,'');}
function downloadFile(msg1,msg2){for(var i=0;i<msg1.length;i++){chrome.downloads.download({url:msg1[i],filename:fixFileName(msg2[i])});}}
function onMp3Click(){chrome.runtime.sendMessage({type:"mp3",},function(response){if(response==="null"){alert('Sorry, Can not find mp3 link!\nPlease try later...');}else{downloadFile([response],[gLinksStorage.fileName+'.mp3']);}});}
function onDownloadClick(){var checkedLinks=new Array();var checkedNames=new Array();var inputTags=document.getElementsByTagName('input');for(var i=0;i<inputTags.length;i++){if(inputTags[i].type=="checkbox"&&inputTags[i].id!=""&&inputTags[i].checked){var linkId=inputTags[i].id.toString().replace(LINK_ROW_ELEM_ID_PREFIX,'');checkedLinks.push(gLinksStorage.fileLink[linkId]);checkedNames.push(gLinksStorage.fileName+" - "+gLinksStorage.fileQuality[linkId]+"."+gLinksStorage.fileType[linkId].split("/")[1]);}}
if(checkedLinks.length<1){return;}
downloadFile(checkedLinks,checkedNames);}
function buildDelimiter(parentElem){var delimDiv=document.createElement('div');delimDiv.name='delim';delimDiv.appendChild(document.createElement('hr'));parentElem.appendChild(delimDiv);}
function setCell(displayText,className){var cell=document.createElement('td');cell.setAttribute('class',className);cell.appendChild(document.createTextNode(displayText));return cell;}
function buildTableHeaderColumn(parentElem,title,className,clmWidth){var elem=document.createElement('th');elem.setAttribute('class',className);elem.appendChild(document.createTextNode(title));elem.setAttribute('width',clmWidth);parentElem.appendChild(elem);}
function buildLinksTableHeader(parentElem){var hdrRow=document.createElement('tr');hdrRow.id='linkTblHeaderRowId';buildTableHeaderColumn(hdrRow,'','chkColmnClass');buildTableHeaderColumn(hdrRow,'Type','linkTableHeaderStyle');buildTableHeaderColumn(hdrRow,'Quality','linkTableHeaderStyle');buildTableHeaderColumn(hdrRow,'Link','linkTableHeaderStyle');if(parentElem.firstChild){parentElem.insertBefore(hdrRow,parentElem.firstChild);}else{parentElem.appendChild(hdrRow);}}
function buildLinkRow(parentElem,linkId){var chkBox=document.createElement('input');chkBox.type="checkbox";chkBox.id=linkId;chkBox.checked=false;chkBox.onclick=function(){onLinkCheck()};var row=document.createElement('tr');row.id=LINK_ROW_ELEM_ID_PREFIX+linkId;var chkCell=document.createElement('td');chkCell.appendChild(chkBox);var typeCell=setCell(gLinksStorage.fileType[linkId],'linksTableCellClass');var linkCell=setCell(gLinksStorage.fileLink[linkId],'linksTableCellClass');var qualityCell=setCell(gLinksStorage.fileQuality[linkId],'linksTableCellClass');row.appendChild(chkCell);row.appendChild(typeCell);row.appendChild(qualityCell);row.appendChild(linkCell);parentElem.appendChild(row);}
function buildTableBody(tblBodyElem){for(var i=0;i<gLinksStorage.count;i++){buildLinkRow(tblBodyElem,i);}}
function buildLinksTable(parentElem){try{var downloadListDiv=document.createElement('div');downloadListDiv.id=DOWNLOAD_LIST_DIV_ID;var table=document.createElement('table');table.id=LINKS_TABLE_ID;table.setAttribute('class',DM_FONT_CLASS);table.setAttribute('cellpadding','0');table.setAttribute('cellspacing','0');var tblBodyElem=document.createElement('tbody');tblBodyElem.id=LINKS_TBL_BODY_ID;buildLinksTableHeader(tblBodyElem);buildTableBody(tblBodyElem);table.appendChild(tblBodyElem);downloadListDiv.appendChild(table);parentElem.appendChild(downloadListDiv);var linksAmount=gLinksStorage.count;var link;for(var i=0;i<linksAmount;i++){if(gLinksStorage.fileType[i]==undefined){link=$('#'+LINK_ROW_ELEM_ID_PREFIX+i);$(link).remove();$('#'+LINKS_TABLE_ID).append(link);}}}catch(e){console.log(e);}}
function appendDownloadElements(parentElement){var downloadElemsDiv=document.createElement('div');var buttonElm=document.createElement('button');buttonElm.setAttribute('class',DM_FONT_CLASS);buttonElm.type='button';buttonElm.innerHTML='Download';buttonElm.onclick=function(){onDownloadClick(this)};downloadElemsDiv.appendChild(buttonElm);parentElement.appendChild(downloadElemsDiv);}
function appendMp3Elements(parentElement){var downloadElemsDiv=document.createElement('div');var buttonElm=document.createElement('button');buttonElm.setAttribute('class',DM_FONT_CLASS);buttonElm.type='button';buttonElm.innerHTML='Get MP3';buttonElm.onclick=function(){onMp3Click(this)};downloadElemsDiv.appendChild(buttonElm);parentElement.appendChild(downloadElemsDiv);}
function buildFooter(parentElem){var footerDiv=document.createElement('div');footerDiv.id=FOOTER_DIV_ID;var btnDiv=document.createElement('div');btnDiv.align='left';appendDownloadElements(btnDiv);var leftClm=document.createElement('td');leftClm.setAttribute('width','20px');leftClm.appendChild(btnDiv);var btnDiv1=document.createElement('div');btnDiv1.align='left';appendMp3Elements(btnDiv1);var leftClm1=document.createElement('td');leftClm1.appendChild(btnDiv1);var row=document.createElement('tr');row.appendChild(leftClm);row.appendChild(leftClm1);var table=document.createElement('table');table.width="100%";table.cellspacing="0";table.cellpadding="0";table.border="0";table.appendChild(row);footerDiv.appendChild(table);parentElem.appendChild(footerDiv);}
window.onload=function windloaded(){chrome.tabs.query({"active":true,"currentWindow":true},function(tabs){linkid=tabs[0].url.substr(32,11);chrome.runtime.sendMessage({type:"getUrls",id:linkid},function(response){gLinksStorage=response;main();});});}
function main(){buildDelimiter(document.body);setExtensionPageWidth();buildLinksTable(document.body);buildDelimiter(document.body);buildFooter(document.body);setExtensionPageHeight();}
function setExtensionPageHeight(extBodyElem){$(document).height(POP_UP_EXT_HEIGHT_MAX);if($(document).height()>POP_UP_EXT_HEIGHT_MAX){$("#"+DOWNLOAD_LIST_DIV_ID).css("overflowY","scroll");var totalWithoutListHeight=$(document).height()-$("#"+DOWNLOAD_LIST_DIV_ID).height();$("#"+DOWNLOAD_LIST_DIV_ID).height(POP_UP_EXT_HEIGHT_MAX-totalWithoutListHeight);}}
function setExtensionPageWidth(){$(document.body).width(POP_UP_EXT_WIDTH_MAX-SCROLLER_WIDTH);}